using System;
using System.Drawing;
using System.Linq;
using System.IO;

namespace GuMaGoChi {
    public static class DefenseTests {
        static int count;
        static void Check(bool ok,string label){if(!ok)throw new Exception("DEFENSE FAIL: "+label);count++;}
        static DefenseBattle Battle(int id){var data=new SaveData();var p=new Pet {SpeciesId=id,Name="시험"};data.Pets.Add(p);var b=new DefenseBattle(data,new[]{p},42);b.Between=0;b.Wave=1;b.Remaining=1;b.SpawnClock=100;b.Team[0].ShotClock=100;return b;}
        public static int Run(){count=0;
            var hopper=new DefenseEnemy {Type=1,Y=480};hopper.Move(.5,44);Check(hopper.X==22&&Math.Abs(hopper.DrawY-435)<.001,"grasshopper lower smooth hop");hopper.Move(.5,44);float landedX=hopper.X;hopper.Move(1.1,44);Check(hopper.X==landedX&&hopper.DrawY==hopper.Y&&hopper.Frame==0,"grasshopper rests on ground after one hop");hopper.Move(.3,44);Check(hopper.X>landedX&&hopper.DrawY<hopper.Y,"grasshopper resumes next hop after rest");
            var stoppedHop=Battle(0);var frozen=stoppedHop.Spawn(1,100,480);frozen.StopTime=1;stoppedHop.Step(.1);Check(frozen.X==100&&frozen.HopClock==0&&frozen.DrawY==480,"stun freezes grasshopper jump and movement");
            var lowerSpawn=Battle(0);lowerSpawn.Team[0].Y=495;lowerSpawn.SpawnClock=0;lowerSpawn.Step(.01);Check(lowerSpawn.Enemies.Count==1&&Math.Abs(lowerSpawn.Enemies[0].Y-495)<=15,"enemies spawn at defender height");var lowerSplit=lowerSpawn.Spawn(3,100,495);lowerSpawn.Kill(lowerSplit);Check(lowerSpawn.Enemies.Where(e=>e.Type==4).All(e=>e.Y>=471&&e.Y<=520),"split enemies retain lower lane");
            var cap=new DefenseBattle(new SaveData(),Enumerable.Range(0,8).Select(i=>new Pet()),42);Check(cap.Team.Count==5,"maximum five defenders");
            Check(DefenseStats.For(-1).Damage==6&&DefenseStats.For(-1).Cooldown==20,"baby weak stats and skill");
            for(int id=0;id<31;id++){var b=Battle(id);var d=b.Team[0];b.Marker=new PointF(550,350);var e=b.Spawn(5,550,350);Check(b.Skill(d),"skill available "+id);Check(d.SkillClock==d.Stats.Cooldown&&d.BubbleClock==2,"cooldown and character dialogue "+id);Check(!b.Skill(d),"no duplicate skill "+id);for(int j=0;j<15;j++)b.Step(.05);Check(!Double.IsNaN(e.HP)&&b.Team.Count==1,"skill simulation "+id);}
            var marker=Battle(26);marker.Team[0].ShotClock=0;marker.Marker=new PointF(550,350);marker.Step(.05);Check(marker.Shots.Count==1,"empty marker still fires");
            var outOfRange=Battle(26);outOfRange.Marker=new PointF(0,500);outOfRange.Team[0].ShotClock=0;outOfRange.Step(.05);Check(outOfRange.Shots.Count==1&&outOfRange.Skill(outOfRange.Team[0]),"full battlefield attack and skill have no range limit");
            var volley=Battle(26);volley.Marker=new PointF(450,350);volley.Skill(volley.Team[0]);Check(volley.Shots.Count==0&&volley.Volleys[0].Count==5,"carrots queued individually");volley.Step(.05);Check(volley.Shots.Count==1&&volley.Volleys[0].Count==4,"first carrot only");volley.Step(.05);Check(volley.Shots.Count==1,"160ms separation");
            var reward=Battle(0);for(int i=0;i<10;i++)reward.Kill(reward.Spawn(0));Check(reward.Data.Seeds==1&&reward.Rewards==1,"one seed per ten kills");var dead=reward.Spawn(0);reward.Kill(dead);reward.Kill(dead);Check(reward.Kills==11,"death counted once");reward.Finish();reward.Finish();Check(reward.Data.Seeds==1,"finish cannot duplicate rewards");
            var split=Battle(0);var parent=split.Spawn(3,600,350);split.Kill(parent);Check(split.Kills==1&&split.Enemies.Count(e=>!e.Dead&&e.Type==4)==3,"split produces three aphids");foreach(var e in split.Enemies.Where(e=>e.Type==4).ToArray())split.Kill(e);Check(split.Kills==4&&split.Enemies.All(e=>e.Dead),"aphids do not split again");
            var armor=Battle(0);var beetle=armor.Spawn(2);double hp=beetle.HP;armor.Damage(beetle,10);Check(Math.Abs(hp-beetle.HP-5.5)<.001,"beetle armor");hp=beetle.HP;armor.Damage(beetle,10,1);Check(Math.Abs(hp-beetle.HP-10)<.001,"armor bypass");
            var boss=armor.Spawn(5);armor.SlowEnemy(boss,.4,4);Check(boss.Slow==.2&&boss.SlowTime==2,"boss control halved");armor.StopEnemy(boss,2);Check(boss.StopTime==1,"boss stun halved");boss.StopTime=0;boss.StopImmune=3;armor.StopEnemy(boss,2);Check(boss.StopTime==0,"stun immunity");
            var wave=Battle(0);wave.Remaining=0;var last=wave.Spawn(3);wave.Kill(last);wave.Step(.05);Check(wave.Completed==0,"wave waits for split children");foreach(var e in wave.Enemies.ToArray())wave.Kill(e);wave.Step(.05);Check(wave.Completed==1&&wave.Between==5&&wave.Data.DefenseBestWave==1,"wave completion and record");
            Check(wave.ChoosingCard&&wave.Cards.Count==3&&wave.Cards.Select(c=>c.Kind).Distinct().Count()==3,"round completion offers three different cards");double waitingTime=wave.Time;for(int i=0;i<100;i++)wave.Step(.1);Check(wave.Wave==1&&wave.Time==waitingTime&&!wave.Skill(wave.Team[0]),"card selection holds next round and skills");Check(wave.Cards.All(c=>c.Kind!=4&&c.Kind!=5),"support-only party receives useful cards instead of skill-damage cards");Check(!wave.ChooseCard(-1)&&!wave.ChooseCard(3)&&wave.Cards.Count==3,"invalid choice cannot consume a card");Check(wave.ChooseCard(0)&&!wave.ChooseCard(0)&&wave.Upgrades.Count==1,"exactly one card can be selected per round");for(int i=0;i<31;i++)wave.Step(.1);Check(wave.Wave==2&&!wave.ChoosingCard,"choice resumes the next round after countdown");
            var toggled=Battle(26);toggled.ToggleMarker(new PointF(100,200));Check(toggled.Marker.Value.X==100,"first shift-click sets marker");toggled.ToggleMarker(new PointF(600,300));Check(!toggled.Marker.HasValue,"second shift-click anywhere clears marker");toggled.ToggleMarker(new PointF(600,300));Check(toggled.Marker.Value.X==600,"third shift-click sets a new marker");
            Check(DefenseStats.For(26).Damage<35&&DefenseStats.For(26).Interval>1.7,"initial damage and attack speed reduced");
            for(int kind=0;kind<8;kind++){
                var cardData=new SaveData();var original=new Pet {SpeciesId=26,Age=500,GrowthExp=180};cardData.Pets.Add(original);cardData.Pets.Add(new Pet {SpeciesId=0});string beforeCard=Storage.Encode(cardData);var upgraded=new DefenseBattle(cardData,cardData.Pets,42);upgraded.Between=0;upgraded.Wave=1;upgraded.Remaining=1;upgraded.SpawnClock=100;var d=upgraded.Team[0];var other=upgraded.Team[1];upgraded.Cards.Add(new DefenseCard(kind,kind%2==0?d:null));Check(upgraded.ChooseCard(0),"card applies "+kind);Check(Storage.Encode(cardData)==beforeCard,"battle upgrade does not mutate raising save "+kind);
                if(kind/2==0){Check(d.AttackPower>d.Stats.Damage&&(kind%2==0?other.AttackPower==other.Stats.Damage:other.AttackPower>other.Stats.Damage),"damage scope is correct "+kind);}
                if(kind/2==1){Check(d.AttackInterval<d.Stats.Interval&&(kind%2==0?other.AttackInterval==other.Stats.Interval:other.AttackInterval<other.Stats.Interval),"speed scope is correct "+kind);}
                if(kind/2==2){Check(d.SkillPower>d.AttackPower&&(kind%2==0?other.SkillPower==other.AttackPower:other.SkillPower>other.AttackPower),"skill-power scope is correct "+kind);}
                if(kind/2==3){Check(d.SkillCooldown<d.Stats.Cooldown&&(kind%2==0?other.SkillCooldown==other.Stats.Cooldown:other.SkillCooldown<other.Stats.Cooldown),"cooldown scope is correct "+kind);}
                upgraded.Between=0;upgraded.Marker=new PointF(550,350);upgraded.Step(.01);var actualShot=upgraded.Shots.First(s=>s.Owner==d);Check(Math.Abs(actualShot.Damage-d.AttackPower)<.001&&Math.Abs(d.ShotClock-d.AttackInterval)<.001,"upgrades drive emitted basic attacks "+kind);Check(upgraded.Skill(d)&&Math.Abs(d.SkillClock-d.SkillCooldown)<.001&&Math.Abs(upgraded.Volleys.First(v=>v.Owner==d).Damage-d.SkillPower*1.2)<.001,"upgrades drive real skill damage and cooldown "+kind);
            }
            var fresh=Battle(26);Check(fresh.Team[0].DamageBonus==1&&fresh.Team[0].SpeedBonus==1&&fresh.Team[0].SkillBonus==1&&fresh.Upgrades.Count==0,"new battle clears previous upgrades");
            for(int i=0;i<40;i++){fresh.Cards.Add(new DefenseCard(2,fresh.Team[0]));fresh.ChooseCard(0);fresh.Cards.Add(new DefenseCard(6,fresh.Team[0]));fresh.ChooseCard(0);}Check(fresh.Team[0].SpeedBonus==4&&fresh.Team[0].SkillCooldown==5,"stacked cards respect attack-speed and cooldown limits");
            var emptyRoster=new DefenseRoster(new Pet[0]);var slotted=new Pet {SpeciesId=26};emptyRoster.Assign(4,slotted);var gap=new DefenseBattle(new SaveData(),emptyRoster.Pets,42);emptyRoster.ApplySlots(gap);Check(gap.Team[0].Slot==4&&emptyRoster.Slots.Take(4).All(p=>p==null),"empty numbered slots are not compressed");Check(!emptyRoster.Assign(-1,slotted)&&!emptyRoster.Assign(5,slotted)&&!emptyRoster.Assign(0,new Pet {Dead=true}),"roster rejects invalid or dead assignments");
            var shield=Battle(7);shield.House=100;shield.Skill(shield.Team[0]);var leak=shield.Spawn(0,949.9f);shield.Step(.05);Check(shield.House==100&&shield.Shield==5,"shield absorbs leak");
            var heal=Battle(20);heal.Skill(heal.Team[0]);Check(heal.House==100,"heal does not exceed maximum");
            var saved=Storage.Decode(Storage.Encode(wave.Data));Check(saved.DefenseBestWave==1&&saved.DefenseBestKills==wave.Kills,"record survives save");
            var old=Storage.Decode("{\"Version\":2,\"Pets\":[],\"Discovered\":[]}");Check(old.DefenseBestWave==0&&old.DefenseBestKills==0,"old save compatible");
            using(var art=new DefenseArt()){foreach(int id in Catalog.Current.Select(s=>s.Id))for(int f=0;f<4;f++){Check(art.Frame("basic-attacks",id,f)!=null,"basic asset "+id+":"+f);Check(art.Frame("skills",id,f)!=null,"skill asset "+id+":"+f);}for(int id=0;id<6;id++)for(int f=0;f<8;f++)Check(art.Frame("enemies",id,f)!=null,"enemy asset "+id+":"+f);Check(art.Missing.Count==0,"complete runtime assets");}
            Check(DefenseBattle.SegmentDistance(new PointF(0,0),new PointF(100,0),new PointF(50,0))==0,"swept collision avoids tunneling");
            foreach(int width in new[]{1920,3840})foreach(int offset in new[]{10,28}){var collision=Battle(26);collision.HitScaleX=width/1000f;collision.HitScaleY=(width*9f/16)/560f;var target=collision.Spawn(0,500,350);collision.Shots.Add(new DefenseShot {Owner=collision.Team[0],Start=new PointF(450,350+offset/collision.HitScaleY),Target=new PointF(700,350+offset/collision.HitScaleY),Point=new PointF(450,350+offset/collision.HitScaleY),Distance=250,Duration=2,Damage=10,Trajectory="straight",Pierce=1});collision.Step(.1);Check((target.HP<target.MaxHP)==(offset==10),"straight hitbox matches physical pixels at "+width+" offset "+offset);}
            foreach(int width in new[]{1920,3840})foreach(int offset in new[]{60,100}){var landing=Battle(1);landing.HitScaleX=width/1000f;landing.HitScaleY=(width*9f/16)/560f;var target=landing.Spawn(0,500,350+offset/landing.HitScaleY);landing.Shots.Add(new DefenseShot {Owner=landing.Team[0],Start=new PointF(450,350),Target=new PointF(500,350),Point=new PointF(450,350),Distance=50,Duration=.1,Damage=10,Trajectory="parabolic",Pierce=1});landing.Step(.1);Check((target.HP<target.MaxHP)==(offset==60),"expanded landing splash physical boundary at "+width+" offset "+offset);}
            foreach(int id in new[]{1,3,18,21}){var zone=Battle(id);zone.Marker=new PointF(500,350);Check(zone.Skill(zone.Team[0]),"zone skill casts "+id);Check(zone.Zones.Single().Radius==170&&zone.Effects.Any(f=>f.Ground&&f.Radius==170),"zone radius and visual doubled "+id);var inside=zone.Spawn(0,500,450);var outside=zone.Spawn(0,500,500);zone.Step(.1);Check(inside.HP<inside.MaxHP||inside.SlowTime>0||inside.Y<450,"expanded zone affects distant enemy "+id);Check(outside.HP==outside.MaxHP&&outside.SlowTime==0&&outside.Y==500,"zone excludes outside enemy "+id);}
            var splash=Battle(1);var nearA=splash.Spawn(0,500,350);var nearB=splash.Spawn(0,500,410);splash.Shots.Add(new DefenseShot {Owner=splash.Team[0],Start=new PointF(450,350),Target=new PointF(500,350),Duration=.1,Damage=10,Trajectory="parabolic"});splash.Step(.1);Check(nearA.HP==nearA.MaxHP-10&&nearB.HP==nearB.MaxHP-10,"parabolic basic damages multiple enemies at impact");
            var enduranceData=new SaveData();var endurance=new DefenseBattle(enduranceData,new[]{26,30,11,20,17}.Select(id=>new Pet {SpeciesId=id}),42);for(int i=0;i<36000&&endurance.Running;i++){if(endurance.ChoosingCard){int best=endurance.Cards.Select((card,index)=>new {card,index}).OrderBy(c=>c.card.Kind/2).First().index;endurance.ChooseCard(best);}foreach(var d in endurance.Team)endurance.Skill(d);endurance.Step(.05);}Check(endurance.Completed>=5,"long battle progresses through boss waves");Check(endurance.Kills/10==endurance.Rewards&&enduranceData.Seeds==endurance.Rewards,"long battle rewards match actual kills");Check(endurance.House>=0&&endurance.House<=100&&!Double.IsNaN(endurance.House),"long battle health remains valid");Check(endurance.Enemies.Count<200&&endurance.Shots.Count<100,"long battle does not accumulate expired actors");endurance.Finish();
            Check(DefenseIntro.FadeOpacity(0)==1&&DefenseIntro.FadeOpacity(3)==1,"intro stays visible for three seconds");Check(Math.Abs(DefenseIntro.FadeOpacity(3.35)-.5)<.001&&DefenseIntro.FadeOpacity(3.7)==.01,"intro fades out after three seconds");
            return count;
        }
        public static string Render(){
            var data=new SaveData {StarterNutrientsClaimed=true};for(int i=0;i<5;i++)data.Pets.Add(new Pet {Name=Catalog.All[new[]{26,30,11,20,23}[i]].Name,SpeciesId=new[]{26,30,11,20,23}[i]});
            var app=new DesktopApp(data,null,false);
            try {using(var window=new DefenseWindow(app)){
                Check(window.AssignSlot(4,data.Pets[0].Id)&&window.Roster.Slots[0].Id==data.Pets[4].Id,"drag assignment swaps occupied numbered slots");
                window.ClearSlot(2);Check(window.Roster.Slots[2]==null,"slot can be emptied before battle");window.AssignSlot(2,data.Pets[2].Id);
                window.Battle=new DefenseBattle(data,window.Roster.Pets,42);window.Roster.ApplySlots(window.Battle);window.Battle.Between=0;window.Battle.Wave=10;window.Battle.Remaining=1;window.Battle.SpawnClock=100;window.Battle.Marker=new PointF(580,350);
                for(int i=0;i<6;i++)window.Battle.Spawn(i,100+i*85,300+i%2*90);
                Rectangle before=window.Bounds;window.EnterDesktop(false);Check(window.FormBorderStyle==System.Windows.Forms.FormBorderStyle.None&&window.TransparencyKey==Color.Magenta,"desktop battlefield remains transparent");
                Check(!window.AssignSlot(0,data.Pets[0].Id),"battle locks party assignment");
                foreach(var d in window.Battle.Team)window.Battle.Skill(d);for(int i=0;i<8;i++)window.Battle.Step(.05);
                using(var bmp=new Bitmap(1920,1080)){using(Graphics g=Graphics.FromImage(bmp))window.Render(g,1920,1080,false);bmp.Save(Path.Combine(Paths.BaseDirectory,"defense-desktop-preview.png"));}
                Check(window.Assets.Missing.Count==0,"runtime effects have no missing sprites");
                Check(DefenseWindow.RosterBounds(1920,1080,true).Width==182,"party panel is narrow");
                var endButton=window.Controls.OfType<System.Windows.Forms.Panel>().SelectMany(p=>p.Controls.OfType<System.Windows.Forms.Button>()).Single(b=>b.Text=="이번 판 종료");Check(endButton.Width>=System.Windows.Forms.TextRenderer.MeasureText(endButton.Text,endButton.Font).Width+16&&endButton.Right<=endButton.Parent.Width,"end button fits complete Korean label with padding");
                for(int slot=0;slot<5;slot++){Rectangle r=DefenseWindow.SlotBounds(1920,1080,true,slot);Check(r.Right<1920&&r.Bottom<1080&&r.Left>1700,"numbered slot stays in bottom-right column");}
                window.Battle.Enemies.Clear();window.Battle.Shots.Clear();window.Battle.Effects.Clear();window.Battle.Marker=null;foreach(var d in window.Battle.Team)d.BubbleClock=0;
                int[] coverage=new int[2];
                for(int n=0;n<2;n++){int width=n==0?1920:3840,height=n==0?1080:2160;using(var screen=new Bitmap(width,height)){using(Graphics g=Graphics.FromImage(screen))window.Render(g,width,height,false);Rectangle r=DefenseWindow.SlotBounds(width,height,true,0);for(int x=r.Left+25;x<r.Left+73;x++)for(int y=r.Top+2;y<r.Top+56;y++){Color c=screen.GetPixel(x,y);if(c.ToArgb()!=Color.OldLace.ToArgb())coverage[n]++;}Check(screen.GetPixel(10,115).ToArgb()==Color.Magenta.ToArgb(),"compact HUD ends before y115");Check(screen.GetPixel((int)(width*.95),(int)(height*.5)).ToArgb()==Color.Magenta.ToArgb(),"old right-side house image removed");screen.Save(Path.Combine(Paths.BaseDirectory,"defense-desktop-"+width+".png"));}}
                Check(coverage[0]>100&&coverage[0]==coverage[1],"slot character size stays identical between HD and 4K");
                string description=DefenseInfo.Describe(window.Battle.Team[0]);Check(description.Contains("고유 특성")&&description.Contains("고유 스킬")&&description.Contains("공격력"),"right-click info contains stats trait and skill");
                window.Battle.Remaining=0;window.Battle.Between=0;window.Battle.Step(.05);window.RefreshCards();Check(window.Battle.ChoosingCard&&window.UpgradePanel.Controls.OfType<System.Windows.Forms.Button>().Count()==3,"upgrade panel exposes three choices");window.ShowInTaskbar=false;window.Location=new Point(-32000,-32000);window.Show();Check(window.UpgradePanel.Controls.OfType<System.Windows.Forms.Button>().All(b=>b.Visible&&b.Text.Contains("%")),"three native card buttons are visible with upgrade details");using(var cards=new Bitmap(window.UpgradePanel.Width,window.UpgradePanel.Height)){window.UpgradePanel.DrawToBitmap(cards,window.UpgradePanel.ClientRectangle);int ink=0;for(int x=0;x<cards.Width;x+=3)for(int y=0;y<cards.Height;y+=3)if(cards.GetPixel(x,y).ToArgb()!=Color.LemonChiffon.ToArgb())ink++;Check(ink>200,"card preview contains visible controls and text");cards.Save(Path.Combine(Paths.BaseDirectory,"defense-card-preview.png"));}window.Hide();
                window.Battle.Finish();window.LeaveDesktop();Check(window.FormBorderStyle==System.Windows.Forms.FormBorderStyle.Sizable&&window.Bounds==before,"battle exit restores setup");
                var startButton=window.PartyPanel.Controls.OfType<System.Windows.Forms.Button>().Single();Check(startButton.Top>window.PartyPanel.Controls.OfType<DefenseSlot>().Max(s=>s.Bottom),"start button does not overlap fifth slot");
                window.Location=new Point(-32000,-32000);window.Show();Check(startButton.Visible&&window.PartyPanel.Controls.OfType<System.Windows.Forms.ListBox>().Single().Visible,"native roster list and start button are visible before battle");using(var setup=new Bitmap(window.PartyPanel.Width,window.PartyPanel.Height)){window.PartyPanel.DrawToBitmap(setup,window.PartyPanel.ClientRectangle);setup.Save(Path.Combine(Paths.BaseDirectory,"defense-party-preview.png"));}endButton.Text="이번 판 종료";using(var header=new Bitmap(endButton.Parent.Width,endButton.Parent.Height)){endButton.Parent.DrawToBitmap(header,endButton.Parent.ClientRectangle);header.Save(Path.Combine(Paths.BaseDirectory,"defense-hud-preview.png"));}using(var info=new DefenseInfo(window.Battle.Team[0])){info.StartPosition=System.Windows.Forms.FormStartPosition.Manual;info.Location=new Point(-32000,-32000);info.Show(window);using(var view=new Bitmap(info.Width,info.Height)){info.DrawToBitmap(view,new Rectangle(0,0,view.Width,view.Height));view.Save(Path.Combine(Paths.BaseDirectory,"defense-info-preview.png"));}}window.Hide();
                int skipped=0;using(var intro=new DefenseIntro(null,new Rectangle(0,0,200,100),()=>skipped++)){typeof(System.Windows.Forms.Control).GetMethod("OnMouseDown",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(intro,new object[]{new System.Windows.Forms.MouseEventArgs(System.Windows.Forms.MouseButtons.Left,1,20,20,0)});intro.Skip();}Check(skipped==1,"intro mouse click skips and finishes exactly once");
                return "Defense render, slots, HUD, info and intro skip passed.";
            }}finally {app.Exit();}
        }
    }
}
