using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Windows.Forms;

namespace GuMaGoChi {
    public sealed class LunchPlan {
        public static readonly string[] Pool={"김치찌개","된장찌개","순두부찌개","부대찌개","청국장","비빔밥","돌솥비빔밥","제육볶음","불고기","백반","돼지국밥","순대국","소고기국밥","콩나물국밥","설렁탕","곰탕","갈비탕","육개장","칼국수","잔치국수","비빔국수","냉면","쌀국수","우동","라멘","막국수","짜장면","짬뽕","볶음밥","마파두부덮밥","잡채밥","돈까스","카레라이스","김밥","떡볶이","만두국","오므라이스","햄버거","샌드위치","파스타","편의점 털기"};
        public readonly string[] Menus;public readonly int[] Bridges=new int[18];readonly double[] phase=new double[5];
        public LunchPlan(Random random,string[] menus=null,string[] pool=null){if(menus!=null)Menus=(string[])menus.Clone();else{var items=(pool??Pool).ToArray();for(int i=items.Length-1;i>0;i--){int j=random.Next(i+1);string swap=items[i];items[i]=items[j];items[j]=swap;}Menus=items.Take(5).ToArray();}for(int i=0;i<5;i++)phase[i]=random.NextDouble()*Math.PI*2;for(int row=0;row<Bridges.Length;row++)Bridges[row]=random.Next(5)-1;}
        public PointF Lane(int lane,double y){return new PointF((float)(90+lane*135+38*Math.Sin(y*Math.PI)*Math.Sin(y*Math.PI*5+phase[lane])),(float)(145+y*390));}
        public PointF Bridge(int row,double t){int left=Bridges[row];double y=(row+1.0)/(Bridges.Length+1);PointF a=Lane(left,y),b=Lane(left+1,y);double u=1-t;return new PointF((float)(u*u*u*a.X+3*u*u*t*(a.X+35)+3*u*t*t*(b.X-35)+t*t*t*b.X),(float)(a.Y+54*u*t));}
        public int Destination(int start){int lane=start;foreach(int left in Bridges)if(left>=0){if(lane==left)lane++;else if(lane==left+1)lane--;}return lane;}
        public List<PointF> Route(int start){var points=new List<PointF>();int lane=start;double previous=0;for(int row=0;row<=Bridges.Length;row++){double end=row==Bridges.Length?1:(row+1.0)/(Bridges.Length+1);for(int step=0;step<=12;step++)points.Add(Lane(lane,previous+(end-previous)*step/12));if(row<Bridges.Length&&Bridges[row]>=0&&(lane==Bridges[row]||lane==Bridges[row]+1)){bool right=lane==Bridges[row];for(int step=1;step<=20;step++)points.Add(Bridge(row,right?step/20.0:1-step/20.0));lane+=right?1:-1;}previous=end;}return points;}
    }
    public sealed class LunchWindow:Form {
        readonly DesktopApp app;readonly Pet pet;readonly Timer timer;readonly Stopwatch clock=Stopwatch.StartNew();readonly Random random=new Random();
        public LunchPlan Plan {get;private set;}List<PointF> route;readonly List<PointF> traveled=new List<PointF>();PointF actor;int next,start=-1;double previous;bool running;string result="";
        readonly Button roll,rebuild,save,edit;readonly Button[] starts=new Button[5];readonly Label status;
        public LunchWindow(DesktopApp owner,Pet chosen){app=owner;pet=chosen;Text="점심 뭐 먹지? · 곡선 사다리";ClientSize=new Size(720,660);FormBorderStyle=FormBorderStyle.FixedSingle;MaximizeBox=false;StartPosition=FormStartPosition.CenterScreen;BackColor=Art.Cream;DoubleBuffered=true;Font=new Font("맑은 고딕",10);
            roll=new Button {Text="메뉴 다시 뽑기",Bounds=new Rectangle(20,15,145,36)};rebuild=new Button {Text="같은 메뉴로 다시 타기",Bounds=new Rectangle(175,15,195,36)};save=new Button {Text="결과 이미지 저장",Bounds=new Rectangle(380,15,155,36),Enabled=false};edit=new Button {Text="메뉴 목록 편집",Bounds=new Rectangle(545,15,155,36)};edit.Click+=(s,e)=>{using(var dialog=new LunchMenuEditor(app.Engine.Data.LunchMenus))if(dialog.ShowDialog(this)==DialogResult.OK){app.Change(()=>app.Engine.Data.LunchMenus=dialog.Menus);Reset(false);}};Controls.AddRange(new Control[]{roll,rebuild,save,edit});status=new Label {Bounds=new Rectangle(20,61,680,36),TextAlign=ContentAlignment.MiddleCenter};Controls.Add(status);
            for(int i=0;i<5;i++){int index=i;starts[i]=new Button {Text=(i+1)+"번 출발",Bounds=new Rectangle(40+i*135,105,100,32)};starts[i].Click+=(s,e)=>Begin(index);Controls.Add(starts[i]);}roll.Click+=(s,e)=>Reset(false);rebuild.Click+=(s,e)=>Reset(true);save.Click+=(s,e)=>Export();timer=new Timer {Interval=20};timer.Tick+=(s,e)=>Frame();FormClosed+=(s,e)=>{timer.Stop();timer.Dispose();if(app.Lunch==this)app.Lunch=null;};Reset(false);timer.Start();}
        void Reset(bool keep){Plan=new LunchPlan(random,keep&&Plan!=null?Plan.Menus:null,app.Engine.Data.LunchMenus.Count>0?app.Engine.Data.LunchMenus.ToArray():null);route=null;traveled.Clear();running=false;start=-1;result="";save.Enabled=false;EnableChoices(true);status.Text="마음에 드는 5개가 나올 때까지 다시 뽑고, 출발점을 선택하세요.";Invalidate();}
        void EnableChoices(bool value){roll.Enabled=rebuild.Enabled=edit.Enabled=value;foreach(var button in starts)button.Enabled=value;}
        public void Begin(int index){if(running||app.Paused)return;start=index;route=Plan.Route(index);actor=route[0];traveled.Clear();traveled.Add(actor);next=1;running=true;EnableChoices(false);save.Enabled=false;status.Text=pet.Name+"가 점심 메뉴를 고르는 중…";previous=clock.Elapsed.TotalSeconds;Invalidate();}
        void Frame(){double now=clock.Elapsed.TotalSeconds,dt=Math.Min(.06,now-previous);previous=now;if(!running)return;if(app.Paused){status.Text="잠시 쉬는 중 · 게임 일시정지를 해제하면 계속합니다.";return;}status.Text=pet.Name+"가 점심 메뉴를 고르는 중…";double budget=160*dt;while(budget>0&&next<route.Count){var target=route[next];double dx=target.X-actor.X,dy=target.Y-actor.Y,len=Math.Sqrt(dx*dx+dy*dy);if(len<=budget){actor=target;traveled.Add(actor);budget-=len;next++;}else{actor=new PointF((float)(actor.X+dx/len*budget),(float)(actor.Y+dy/len*budget));budget=0;}}if(next>=route.Count){running=false;result=Plan.Menus[Plan.Destination(start)];status.Text="오늘은 "+result+"! · "+pet.Name+"의 선택";EnableChoices(true);save.Enabled=true;}Invalidate();}
        protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.SmoothingMode=SmoothingMode.AntiAlias;using(var line=new Pen(Color.FromArgb(139,110,87),3))using(var highlight=new Pen(Color.FromArgb(233,147,50),5)){
                for(int lane=0;lane<5;lane++){var points=new PointF[121];for(int i=0;i<=120;i++)points[i]=Plan.Lane(lane,i/120.0);g.DrawLines(line,points);}for(int row=0;row<Plan.Bridges.Length;row++)if(Plan.Bridges[row]>=0){var points=new PointF[21];for(int i=0;i<=20;i++)points[i]=Plan.Bridge(row,i/20.0);g.DrawLines(line,points);foreach(var end in new[]{points[0],points[20]})g.FillEllipse(Brushes.SaddleBrown,end.X-4,end.Y-4,8,8);}if(traveled.Count>1)g.DrawLines(highlight,traveled.ToArray());if(running&&traveled.Count>0)g.DrawLine(highlight,traveled[traveled.Count-1],actor);
            }for(int i=0;i<5;i++){var rect=new Rectangle(30+i*135,549,120,48);if(result!=""&&i==Plan.Destination(start))g.FillRectangle(Brushes.PaleGoldenrod,rect);TextRenderer.DrawText(g,Plan.Menus[i],Font,rect,Color.SaddleBrown,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter|TextFormatFlags.WordBreak);}if(route!=null)Art.Pet(g,pet,new Rectangle((int)actor.X-30,(int)actor.Y-58,60,60),clock.Elapsed.TotalSeconds,"walk");TextRenderer.DrawText(g,(app.Engine.Data.LunchMenus.Count>0?"내 메뉴 "+app.Engine.Data.LunchMenus.Count+"개":"기본 메뉴 41개")+" 중 5개 · 추첨 횟수 제한 없음 · 씨앗 소모 없음",Font,new Rectangle(20,615,680,30),Color.SaddleBrown,TextFormatFlags.HorizontalCenter);}
        void Export(){using(var dialog=new SaveFileDialog {Filter="PNG 이미지|*.png",FileName="GuMaGoChi-점심메뉴.png"})if(dialog.ShowDialog(this)==DialogResult.OK)try{using(var image=new Bitmap(ClientSize.Width,ClientSize.Height)){DrawToBitmap(image,new Rectangle(Point.Empty,ClientSize));image.Save(dialog.FileName,ImageFormat.Png);}}catch(Exception ex){MessageBox.Show(this,"이미지 저장 실패: "+ex.Message);}}
    }
    public static class LunchTests {
        public static int Run(){int count=0;var random=new Random(12);if(LunchPlan.Pool.Length!=41||LunchPlan.Pool.Distinct().Count()!=41||!LunchPlan.Pool.Contains("편의점 털기"))throw new Exception("Lunch menu catalog");count++;
            var custom=LunchMenuEditor.Parse("회사 앞 김밥\r\n 국밥 \n회사 앞 김밥\n\n백반\n돈까스\n편의점 털기");if(custom.Count!=5||custom[1]!="국밥")throw new Exception("Lunch pasted menu normalize");count++;
            var customPlan=new LunchPlan(random,null,custom.ToArray());if(customPlan.Menus.Any(m=>!custom.Contains(m)))throw new Exception("Lunch custom pool only");count++;
            var customData=new SaveData {LunchMenus=custom};if(!Storage.Decode(Storage.Encode(customData)).LunchMenus.SequenceEqual(custom))throw new Exception("Lunch custom save roundtrip");count++;
            customData.LunchMenus=new List<string>{"한 개"};bool rejected=false;try{Storage.Decode(Storage.Encode(customData));}catch(InvalidDataException){rejected=true;}if(!rejected)throw new Exception("Lunch invalid custom pool");count++;
            for(int sample=0;sample<100;sample++){var plan=new LunchPlan(random);if(plan.Menus.Length!=5||plan.Menus.Distinct().Count()!=5)throw new Exception("Lunch unique draw");count++;if(Enumerable.Range(0,5).Select(plan.Destination).Distinct().Count()!=5)throw new Exception("Lunch destinations permutation");count++;for(int i=0;i<5;i++){var path=plan.Route(i);if(path[0]!=plan.Lane(i,0)||path[path.Count-1]!=plan.Lane(plan.Destination(i),1))throw new Exception("Lunch route follows fixed outcome");count++;}var same=new LunchPlan(random,plan.Menus);if(!same.Menus.SequenceEqual(plan.Menus)||ReferenceEquals(same.Menus,plan.Menus))throw new Exception("Lunch preserve menu independent plan");count++;}
            var data=new SaveData();data.Pets.Add(new Pet {Active=false});using(var app=new DesktopApp(data,null,false))using(var window=new LunchWindow(app,new Pet {Name="점심 고구마",SpeciesId=12,EvolutionId=6})){window.Show();Application.DoEvents();using(var image=new Bitmap(window.Width,window.Height)){window.DrawToBitmap(image,new Rectangle(0,0,image.Width,image.Height));image.Save(Path.Combine(Paths.BaseDirectory,"lunch-preview.png"));}window.Close();app.Exit();}return count;
        }
    }
}
