using System;
using System.Drawing;
using System.IO;
using System.Windows.Forms;

namespace GuMaGoChi {
    public static class RunnerTests {
        static int count;
        static void Check(bool ok,string label){if(!ok)throw new Exception("RUNNER FAIL: "+label);count++;}
        public static int Run(){
            count=0;var r=new EdgeRun(1200,700,7);PointF p;float angle;
            using(var actorMask=new Bitmap(20,20))using(var bugMask=new Bitmap(20,20))using(var collision=new RunnerCollision()){
                actorMask.SetPixel(5,10,Color.Purple);bugMask.SetPixel(5,10,Color.Green);
                Check(collision.Test(actorMask,new PointF(30,30),0,bugMask,new PointF(30,30),0),"opaque pixels collide");
                Check(!collision.Test(actorMask,new PointF(30,30),0,bugMask,new PointF(31,30),0),"separated silhouettes do not collide after reused hit");
                Check(!collision.Test(actorMask,new PointF(30,30),0,bugMask,new PointF(30,30),90),"rotation affects silhouette");
                Check(collision.Test(actorMask,new PointF(30,30),90,bugMask,new PointF(30,30),90),"rotated pixels collide");
                Check(!collision.Test(actorMask,new PointF(30,30),0,bugMask,new PointF(300,300),0),"distant silhouettes do not collide");
            }
            r.Distance=r.Obstacles[0].Distance-5;r.Tick(.02,()=>false);Check(!r.Finished,"silhouette callback overrides fallback");r.Tick(.02,()=>true);Check(r.Finished,"silhouette overlap ends run");
            r=new EdgeRun(1200,700,7);r.Point(100,42,out p,out angle);Check(p.X==280&&p.Y==658&&angle==0,"bottom straight");
            double arc=Math.PI*(r.CornerRadius-42)/2,sw=r.Width-2*r.CornerRadius,sh=r.Height-2*r.CornerRadius;
            r.Point(sw+arc/2,42,out p,out angle);Check(Math.Abs(angle-315)<.001,"rounded right turn midpoint");
            double travelled=0;double[] segments={sw,arc,sh,arc,sw,arc,sh,arc};
            foreach(double segment in segments){travelled+=segment;PointF before,after;float a,b;r.Point(travelled-.01,42,out before,out a);r.Point(travelled+.01,42,out after,out b);double turn=Math.Abs(a-b);turn=Math.Min(turn,360-turn);Check(Math.Abs(before.X-after.X)<.1&&Math.Abs(before.Y-after.Y)<.1&&turn<.1,"continuous position and rotation at boundary");}
            foreach(var bounds in new[]{new Size(640,480),new Size(1200,700),new Size(3840,2160)}){
                var path=new EdgeRun(bounds.Width,bounds.Height,7);for(double distance=0;distance<path.Length;distance+=17){path.Point(distance,119,out p,out angle);double radians=angle*Math.PI/180,extent=42*(Math.Abs(Math.Cos(radians))+Math.Abs(Math.Sin(radians)));Check(p.X>=extent&&p.X<=path.Width-extent&&p.Y>=extent&&p.Y<=path.Height-extent,"jumped rotated sprite stays on screen");}
            }
            for(double distance=0;distance<r.Length;distance+=7){PointF a,b;r.Point(distance,42,out a,out angle);r.Point(distance+.1,42,out b,out angle);double length=Math.Sqrt((a.X-b.X)*(a.X-b.X)+(a.Y-b.Y)*(a.Y-b.Y));Check(Math.Abs(length-.1)<.001,"constant ground speed through corners");}
            r.Point(0,42,out p,out angle);PointF wrap;float rotation;r.Point(r.Length,42,out wrap,out rotation);Check(p==wrap&&angle==rotation,"continuous lap wrap");
            double first=r.Obstacles[0].Distance;r.MoveObstacles(.1);Check(r.Obstacles[0].Distance<first,"crawlers move opposite runner");
            Check(r.ChooseKind(119,.01)==RunnerObstacleKind.Crawler,"early tier only crawlers");Check(r.ChooseKind(120,.2)==RunnerObstacleKind.Grasshopper,"middle tier grasshopper");Check(r.ChooseKind(299,.01)==RunnerObstacleKind.Grasshopper,"no mole before high tier");Check(r.ChooseKind(300,.05)==RunnerObstacleKind.Mole,"rare high tier mole");
            int moles=0;for(int i=0;i<100;i++)if(r.ChooseKind(300,i/100.0)==RunnerObstacleKind.Mole)moles++;Check(moles==10,"mole weight is ten percent");r.Distance=200000;Check(r.WarningTime>=.85,"warning has minimum reaction time");
            var grass=new RunObstacle {Kind=RunnerObstacleKind.Grasshopper};grass.Update(.01,200,250,1);Check(grass.State==RunnerObstacleState.Warning&&grass.Height==0,"grasshopper crouches before jumping");for(int i=0;i<90;i++)grass.Update(.01,200,250,1);Check(grass.State==RunnerObstacleState.Warning,"warning lasts before takeoff");for(int i=0;i<60;i++)grass.Update(.01,100,250,1);Check(grass.State==RunnerObstacleState.Active&&grass.Height>100,"grasshopper jumps after warning");for(int i=0;i<100;i++)grass.Update(.01,100,250,1);Check(grass.Height==0,"grasshopper returns to ground");
            var mole=new RunObstacle {Kind=RunnerObstacleKind.Mole};mole.Update(.01,100,250,1);Check(mole.Visible&&!mole.Collidable&&mole.State==RunnerObstacleState.Warning,"soil warning is visible and harmless");for(int i=0;i<120;i++)mole.Update(.01,40,250,1);Check(mole.Collidable&&mole.Emergence>.9,"mole emerges after full warning");for(int i=0;i<90;i++)mole.Update(.01,40,250,1);Check(!mole.Collidable,"mole retracts without repeated attacks");
            using(var art=new RunnerObstacleArt())using(var image=new Bitmap(720,240))using(var g=Graphics.FromImage(image)){
                g.Clear(Art.Cream);var states=new[]{new RunObstacle {Kind=RunnerObstacleKind.Crawler},new RunObstacle {Kind=RunnerObstacleKind.Grasshopper,State=RunnerObstacleState.Warning},new RunObstacle {Kind=RunnerObstacleKind.Grasshopper,State=RunnerObstacleState.Active,Clock=.5},new RunObstacle {Kind=RunnerObstacleKind.Mole,State=RunnerObstacleState.Warning},new RunObstacle {Kind=RunnerObstacleKind.Mole,State=RunnerObstacleState.Active,Clock=.25}};
                string[] names={"Crawler","Grass: crouch","Grass: jump","Mole: soil warning","Mole: emerge"};for(int i=0;i<states.Length;i++){var bitmap=art.Image(states[i],.24);Check(bitmap!=null&&bitmap.Width>=48,"obstacle pose asset");RunnerCollision.Draw(g,bitmap,new PointF(70+i*140,165-(float)states[i].Height),0);g.DrawString(names[i],SystemFonts.DefaultFont,Brushes.Black,8+i*140,210);}image.Save(Path.Combine(Paths.BaseDirectory,"runner-obstacles-preview.png"));
            }
            r=new EdgeRun(1200,700,7);r.Jump();r.Tick(.1,()=>false);Check(r.JumpHeight>30,"jump rises");double velocity=r.Velocity;r.Jump();Check(r.Velocity==velocity,"no midair double jump");r.Tick(.4,()=>false);r.Tick(.16,()=>false);r.Jump();r.Tick(.08,()=>false);Check(r.Velocity>0,"buffered input jumps on landing");
            var slow=new EdgeRun(1200,700,7);slow.Tick(.25,()=>false);Check(Math.Abs(slow.Elapsed-.25)<.0001,"delayed frame time is preserved");
            r=new EdgeRun(1200,700,7);for(int i=0;i<1000&&!r.Finished;i++)r.Tick(.02);Check(r.Finished,"ground collision");double frozen=r.Distance,obstaclePosition=r.Obstacles[0].Distance;r.Tick(.1);r.Jump();Check(r.Distance==frozen&&r.Obstacles[0].Distance==obstaclePosition,"finished run freezes");
            var data=new SaveData();var date=new DateTime(2026,10,5);Check(EdgeRun.Reward(data,9,date)==0&&data.RunnerBest==9,"short run no farming reward");Check(EdgeRun.Reward(data,600,date)==6,"run reward cap");for(int i=0;i<5;i++)EdgeRun.Reward(data,600,date);Check(data.RunnerRewardPaid==20&&data.Seeds==20,"daily cap");Check(EdgeRun.Reward(data,300,date.AddDays(1))==3&&data.RunnerBest==600,"daily reset keeps record");var loaded=Storage.Decode(Storage.Encode(data));Check(loaded.RunnerBest==600&&loaded.RunnerRewardPaid==3,"record roundtrip");
            var fixture=new SaveData();fixture.Pets.Add(new Pet {Active=false});using(var app=new DesktopApp(fixture,null,false))using(var window=new RunnerWindow(app,new Pet {Name="달리기 시범",SpeciesId=12,EvolutionId=6}))using(var image=window.RecordImage()){Check(image.Width==720&&image.Height==360,"share image size");image.Save(Path.Combine(Paths.BaseDirectory,"runner-record-preview.png"));window.Show();Application.DoEvents();using(var screen=new Bitmap(window.Width,window.Height)){window.DrawToBitmap(screen,new Rectangle(0,0,screen.Width,screen.Height));screen.Save(Path.Combine(Paths.BaseDirectory,"runner-preview.png"));}app.Exit();}
            CheckEncounter(RunnerObstacleKind.Grasshopper,false,false);CheckEncounter(RunnerObstacleKind.Grasshopper,false,true,false);CheckEncounter(RunnerObstacleKind.Grasshopper,true,false,false);CheckEncounter(RunnerObstacleKind.Mole,false,true);CheckEncounter(RunnerObstacleKind.Mole,true,false);
            foreach(bool willJump in new[]{true,false}){var choice=new RunObstacle {Kind=RunnerObstacleKind.Grasshopper,WillJump=willJump};choice.Update(.01,200,250,1);Check(choice.Speech=="뛸까말까~"&&!choice.JumpPreparation,"shared thinking phase");for(int i=0;i<40;i++)choice.Update(.01,150,250,1);Check(choice.Speech==(willJump?"뛰어야지!":"안뛸래~")&&choice.JumpPreparation==willJump,"announced choice matches preparation");for(int i=0;i<80;i++)choice.Update(.01,100,250,1);Check(choice.State==RunnerObstacleState.Active&&(choice.Height>0)==willJump,"announced choice matches actual motion");choice.Pending=true;Check(!choice.Collidable,"pending grasshopper is harmless");}
            var recycle=new EdgeRun(1200,700,9);recycle.Distance=6000;recycle.Obstacles.Clear();var recycled=new RunObstacle {Distance=(recycle.Distance-200)%recycle.Length,Encountered=true};recycle.Obstacles.Add(recycled);recycle.MoveObstacles(.01);Check(!recycled.Pending&&recycle.Ahead(recycled.Distance)>360,"replacement spawns ahead with reaction distance");
            return count;
        }
        static void CheckEncounter(RunnerObstacleKind kind,bool jump,bool expectedHit,bool willJump=true){var run=new EdgeRun(1200,700,9);run.Obstacles.Clear();var obstacle=new RunObstacle {Kind=kind,WillJump=willJump,Distance=kind==RunnerObstacleKind.Mole?300:420};run.Obstacles.Add(obstacle);using(var art=new RunnerObstacleArt())using(var actor=new Bitmap(84,84))using(var collision=new RunnerCollision()){using(var g=Graphics.FromImage(actor))Art.Pet(g,new Pet {SpeciesId=0},new Rectangle(0,0,84,84),0,"walk");bool jumped=false;for(int tick=0;tick<240&&!run.Finished;tick++){if(jump&&!jumped&&run.Ahead(obstacle.Distance)<(kind==RunnerObstacleKind.Grasshopper?110:60)){run.Jump();jumped=true;}run.Tick(.01,()=>{if(!obstacle.Collidable)return false;PointF a,b;float angle,rotation;run.Point(run.Distance,42+run.JumpHeight,out a,out angle);var image=art.Image(obstacle,run.Elapsed);run.Point(obstacle.Distance,image.Height/2.0+obstacle.Height,out b,out rotation);return collision.Test(actor,a,angle,image,b,rotation);});}Check(run.Finished==expectedHit,kind+" telegraph encounter with jump="+jump+" elapsed="+run.Elapsed+" height="+run.JumpHeight+" ahead="+run.Ahead(obstacle.Distance)+" state="+obstacle.State+" clock="+obstacle.Clock);}}
    }
}
